RPI-evo-model: *.cc *.h
	${GXX} main.cc Vertex.cc Group.cc Network.cc Edge.cc -o RPI-evo-model -L../../Libraries/Files -lfiles -L../../Libraries/Random -lRandom -L../../Libraries/Params -lParams -g -std=c++11
